modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="clockwise"
version="${file.jarVersion}"
displayName="Clockwise"
# logoFile="clockwise.png"
authors="TurtyWurty"
displayTest="MATCH_VERSION"
description='''A mod that adds clocks.'''

[[dependencies.clockwise]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.clockwise]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
